# Generated by Django 5.1.6 on 2025-02-13 16:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_alter_category_slug_alter_post_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="name",
            new_name="title",
        ),
    ]
