# Generated by Django 5.1.6 on 2025-02-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_page"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="categories",
        ),
        migrations.AddField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(blank=True, null=True, to="blog.category"),
        ),
    ]
