# Generated by Django 5.1.6 on 2025-02-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_remove_post_categories_post_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.FileField(blank=True, upload_to="images"),
        ),
    ]
